### ISSUE TITLE
Allow users to upload custom baselines

### ISSUE THREAD

**Issue by fkryvyts-codete** [codete/QAcheck#2]
Instead of using current screenshots as new baselines allow user to be also able to upload custom, modified screenshot as new baseline for test step

**Comment by dmkomarov-codete** [comment]
Implemented functionality to upload custom baselines.
Commit ids:
c17eb4f7ad413ad78ec2b1c1454a25798316094c
305f89d5bea8d18b2d986aebf45b199eb23c2bd7
