### ISSUE TITLE
Introduce database migrations for project

### ISSUE THREAD

**Issue by fkryvyts-codete** [codete/QAcheck#6]
Instead of using Hibernate's ddl-auto we need to introduce proper migrations to the project.  Ideally would be if we can use flyway: https://www.callicoder.com/spring-boot-flyway-database-migration-example/

**Comment by dmkomarov-codete** [comment]
Added flyway migrations.
Commit id: 6f9aa66af1c024cb8f91dc68bc938de28d10e886
